### ISSUE TITLE
Regarding API endpoints

### ISSUE THREAD

**Issue by AkhilLV** [RijoBiju/CarManagement#1]
Endpoints with request formats

### Cars

- [x] **/POST** to /cars

```
{
  carBrand,
  carModel,
  carPlate
}
```
- [x] **/PATCH** to /cars/:carId/basic

```
{
  carBrand,
  carModel,
  carPlate,
  yearOfManufacture,
  mileage
}
```

- [x] **/PATCH** to /cars/:carId/selling

```
{
  msp,
  customerDeliveryFees,
  marketValue
}
```

- [x] **/GET** to /cars/:carId

Response format:
```
{
  carId,
  carBrand,
  carModel,
  carPlate,
  yearOfManufacture,
  mileage,
  Minimum Selling Price,
  Customer Delivery Fee,
  Present market value
}
```

- [x] **/GET** to /cars

```
[
  {
  carId,
  carBrand,
  carModel,
  carPlate,
  yearOfManufacture,
  mileage,
  Minimum Selling Price,
  },
  ...
]
```

- [x] **/PATCH** to /cars/:carId/archive

```
{
  archive: true | false
}
```
### Expense Types

- [x] **/POST** to /expense-type

```
{
  expenseName,
  colorCode
}
```

- [x] **/GET** to /expense-type

```
[
  {
  expenseName,
  colorCode
  },
  ...
]
```

**Comment by RijoBiju** [comment]
i don't find this to be an issue

**Comment by RijoBiju** [comment]
@AkhilLV shouldn't there be a link between expensetype and car ?

**Comment by AkhilLV** [comment]
> @AkhilLV shouldn't there be a link between expensetype and car ?

Yes. But this is not for an individual expense. This is for an expense type
![image](https://github.com/user-attachments/assets/f2967729-99d0-4707-b090-9f0f969622c7)

**Comment by RijoBiju** [comment]
pleasure working with you. pls write to me if necessary.
